### ISSUE TITLE
category api bugs

### ISSUE THREAD

**Issue by ganeshparajuli** [ganeshparajuli/seoblog#11]
[TypeError: Cannot read property '_id' of undefined when giving POST
`POST /api/category 500 4.484 ms - 1145
TypeError: Cannot read property '_id' of undefined
    at exports.adminMiddleware (C:\Users\spybot\project\seoblog\backend\controllers\auth.js:89:34)
    at Layer.handle [as handle_request] (C:\Users\spybot\project\seoblog\backend\node_modules\express\lib\router\layer.js:95:5)  `
solution:
exports.requireSignin = expressjwt({
    secret: process.env.JWT_SECRET,
    algorithms: ["HS256"],
    requestProperty: "user",
});
![image](https://user-images.githubusercontent.com/49775419/172052455-cc03297f-f4fa-4344-8b61-7aa25e60fd3d.png)

**Comment by ganeshparajuli** [comment]
TypeError: Cannot read property '_id' of undefined
    at exports.adminMiddleware (C:\Users\spybot\project\seoblog\backend\controllers\auth.js:89:34)
    at Layer.handle [as handle_request] (C:\Users\spybot\project\seoblog\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\spybot\project\seoblog\backend\node_modules\express\lib\router\route.js:144:13)
    at C:\Users\spybot\project\seoblog\backend\node_modules\express-jwt\dist\index.js:148:25
    at step (C:\Users\spybot\project\seoblog\backend\node_modules\express-jwt\dist\index.js:33:23)
    at Object.next (C:\Users\spybot\project\seoblog\backend\node_modules\express-jwt\dist\index.js:14:53)
    at fulfilled (C:\Users\spybot\project\seoblog\backend\node_modules\express-jwt\dist\index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
