### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: 

### ISSUE THREAD

**Issue by ganeshparajuli** [ganeshparajuli/seoblog#14]
internal/modules/cjs/loader.js:1089

      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);

      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\.......blog\backend\node_modules\string-strip-html\dist\string-strip-html.esm.js

require() of ES modules is not supported.

require() of C:\............blog\backend\node_modules\string-strip-html\dist\string-strip-html.esm.js from C:\...........blog\backend\controllers\blog.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

Instead rename string-strip-html.esm.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\...........blog\backend\node_modules\string-strip-html\package.json.

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)

    at Module.load (internal/modules/cjs/loader.js:937:32)

    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

    at Module.require (internal/modules/cjs/loader.js:961:19)

    at require (internal/modules/cjs/helpers.js:92:18)

    at Object.<anonymous> (C://........../backend\controllers\blog.js:10:19)

    at Module._compile (internal/modules/cjs/loader.js:1072:14)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

    at Module.load (internal/modules/cjs/loader.js:937:32)

    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {

  code: 'ERR_REQUIRE_ESM'

**Comment by ganeshparajuli** [comment]
solution: npm i string-strip-html@8.3.0
